# Step metadata example - full description at:
# https://github.com/puppetlabs/relay-rfcs/blob/master/content/0006-integration-layout/rfc.md#common-metadata
apiVersion: integration/v1
kind: Step
name: powershell-step-run
version: 1
summary: Run PowerShell script
description: |
  Relay step for running a PowerShell script (inline or from a URL).

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/powershell-step-run

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
    - summary: Run inline powershell script
      content:
        apiVersion: v1
        kind: Step
        name: run-powershell-from-git
        image: relaysh/powershell-step-run
        spec:
          script: |
            Write-Host "Hello World!"
            Write-Host "Hello Puppet!"

    - summary: Run powershell script from a URL
      content:
        apiVersion: v1
        kind: Step
        name: run-powershell-from-url
        image: relaysh/powershell-step-run
        spec:
          scriptUrl: "https://example.com/myscript.ps1"

    - summary: Run powershell script from a git repo
      content:
        apiVersion: v1
        kind: Step
        name: run-powershell-from-git
        image: relaysh/powershell-step-run
        spec:
          git:
            connection: ${connections.ssh.'my-ssh-connection'}
            repository: git@github.com:someuser/somerepo
            branch: main
            scriptPath: powershell/sample.ps1

